# Generated by Django 4.0.2 on 2022-02-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_userrelationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrelationship',
            old_name='rel_type',
            new_name='relation_type',
        ),
    ]
