# Generated by Django 4.0.2 on 2022-02-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_rename_rel_type_userrelationship_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelationship',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
