# Generated by Django 4.0.2 on 2022-02-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0009_post'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('image', None), ('text__isnull', False)), models.Q(('image__isnull', False), ('text', None)), _connector='OR'), name='Image or text should not be empty.'),
        ),
    ]
